name : Build and Deploy Spring Boot to AWS EC2

on:
  push:
    branches : [ "master" ]
  pull_request :
    branches : [ "master" ]


#---------------------------------------------------
env:
  PROJECT_NAME : FoDong_Project
  BUCKET_NAME : fodongbucket
  CODE_DEPLOY_NAME : fodong_cicd
  DEPLOYMENT_GROUP_NAME : fodong-cicd-codedeploy-group
#---------------------------------------------------

permissions :
  contents : read

jobs:
  build:
    runs-on : ubuntu-latest

    steps:
      - name : Checkout
        uses: actions/checkout@v3

      - name : Set up JDK 11
        uses : actions/setup-java@v3
        with :
          java-version : 11
          distribution: 'temurin'

      - name : permission for gradlew
        run : chmod +x ./gradlew
        shell : bash

      - name: Build and Test
        run: ./gradlew build test

      - name : Set database YML
        run: |
          touch ./src/main/resources/application-real.yml
          echo "${{ secrets.APPLICATION_REAL_YML }}" | base64 --decode > src/main/resources/application-real.yml

      #---------------------------------------------------

      - name : Make Directory for deliver
        run: mkdir fodongServer

      - name : Copy jar
        run: cp ./build/libs/*.jar ./fodongServer/

      - name : Copy appspec
        run: cp appspec.yml ./fodongServer

      - name : Make Zip File
        run : zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name : Deliver to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PRIVATE_ACCESS_KEY }}
        run: |
          aws s3 cp \
          --region ap-northeast-2 \
          --acl private \
          ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

        #Deploy
      - name : Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PRIVATE_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2
        run: |
          aws deploy create-deployment \
          --application-name $CODE_DEPLOY_NAME \
          --deployment-group-name $DEPLOYMENT_GROUP_NAME \
          --file-exists-behavior OVERWRITE \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip